version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
  #  depends_on:
  #    - wordpress
    restart: on-failure

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT=${DB_ROOT}
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    restart: on-failure

volumes:
  db-volume: